AWSTemplateFormatVersion: 2010-09-09
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: std21011
  SsmArnName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["", [test, -s3, -bucket]]
      Type: String
      Value: !GetAtt Bucket.Arn
  
